//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference2.SqlInfo[] SqlinfoListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference2.SqlInfo[] SqlinfoList {
            get {
                return this.SqlinfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.SqlinfoListField, value) != true)) {
                    this.SqlinfoListField = value;
                    this.RaisePropertyChanged("SqlinfoList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlInfo", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class SqlInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string befnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string changenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string befnum {
            get {
                return this.befnumField;
            }
            set {
                if ((object.ReferenceEquals(this.befnumField, value) != true)) {
                    this.befnumField = value;
                    this.RaisePropertyChanged("befnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string changenum {
            get {
                return this.changenumField;
            }
            set {
                if ((object.ReferenceEquals(this.changenumField, value) != true)) {
                    this.changenumField = value;
                    this.RaisePropertyChanged("changenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.datetimeField, value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenum {
            get {
                return this.prenumField;
            }
            set {
                if ((object.ReferenceEquals(this.prenumField, value) != true)) {
                    this.prenumField = value;
                    this.RaisePropertyChanged("prenum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Register_Sql", ReplyAction="http://tempuri.org/IService2/Register_SqlResponse")]
        int Register_Sql(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Register_Sql", ReplyAction="http://tempuri.org/IService2/Register_SqlResponse")]
        System.Threading.Tasks.Task<int> Register_SqlAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Login_Sql", ReplyAction="http://tempuri.org/IService2/Login_SqlResponse")]
        bool Login_Sql(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Login_Sql", ReplyAction="http://tempuri.org/IService2/Login_SqlResponse")]
        System.Threading.Tasks.Task<bool> Login_SqlAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/querySql", ReplyAction="http://tempuri.org/IService2/querySqlResponse")]
        Client.ServiceReference2.CompositeType querySql(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/querySql", ReplyAction="http://tempuri.org/IService2/querySqlResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference2.CompositeType> querySqlAsync(string UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Client.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Client.ServiceReference2.IService2>, Client.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register_Sql(string username, string password) {
            return base.Channel.Register_Sql(username, password);
        }
        
        public System.Threading.Tasks.Task<int> Register_SqlAsync(string username, string password) {
            return base.Channel.Register_SqlAsync(username, password);
        }
        
        public bool Login_Sql(string username, string password) {
            return base.Channel.Login_Sql(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> Login_SqlAsync(string username, string password) {
            return base.Channel.Login_SqlAsync(username, password);
        }
        
        public Client.ServiceReference2.CompositeType querySql(string UserName) {
            return base.Channel.querySql(UserName);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference2.CompositeType> querySqlAsync(string UserName) {
            return base.Channel.querySqlAsync(UserName);
        }
    }
}
