//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WcfChat", ConfigurationName="ServiceReference1.IService", CallbackContract=typeof(Client.ServiceReference1.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Login")]
        void Login();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Login")]
        System.Threading.Tasks.Task LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Logout")]
        void Logout(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Logout")]
        System.Threading.Tasks.Task LogoutAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/SitDown")]
        void SitDown(string userName, int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/SitDown")]
        System.Threading.Tasks.Task SitDownAsync(string userName, int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/GetUp")]
        void GetUp(int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/GetUp")]
        System.Threading.Tasks.Task GetUpAsync(int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Start")]
        void Start(string userName, int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Start")]
        System.Threading.Tasks.Task StartAsync(string userName, int index, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/SetDot")]
        void SetDot(int index, int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/SetDot")]
        System.Threading.Tasks.Task SetDotAsync(int index, int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Talk")]
        void Talk(int index, string userName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Talk")]
        System.Threading.Tasks.Task TalkAsync(int index, string userName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/randomplace")]
        void randomplace(int index);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/randomplace")]
        System.Threading.Tasks.Task randomplaceAsync(int index);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/userset")]
        void userset(int index, string username, int clickid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/userset")]
        System.Threading.Tasks.Task usersetAsync(int index, string username, int clickid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/TalkToSomebody")]
        void TalkToSomebody(string sender, string receiver, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/TalkToSomebody")]
        System.Threading.Tasks.Task TalkToSomebodyAsync(string sender, string receiver, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowLogin")]
        void ShowLogin(string loginUserName, int maxTables);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowLogout")]
        void ShowLogout(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowSitDown")]
        void ShowSitDown(string userName, int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowGetUp")]
        void ShowGetUp(int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowStart")]
        void ShowStart(int side);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowTalk")]
        void ShowTalk(string messageTpye, string userName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowSetDot")]
        void ShowSetDot(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/GameStart")]
        void GameStart();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/GameWin")]
        void GameWin(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/UpdateTablesInfo")]
        void UpdateTablesInfo(string tablesInfo, int userCount);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/Gotscore")]
        void Gotscore(string message, string message1, string message3);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ResetGrid")]
        void ResetGrid();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/InitUsersInfo")]
        void InitUsersInfo(string UsersInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfChat/IService/ShowStar")]
        void ShowStar(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference1.IService>, Client.ServiceReference1.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login() {
            base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public void Logout(string userName) {
            base.Channel.Logout(userName);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string userName) {
            return base.Channel.LogoutAsync(userName);
        }
        
        public void SitDown(string userName, int index, int side) {
            base.Channel.SitDown(userName, index, side);
        }
        
        public System.Threading.Tasks.Task SitDownAsync(string userName, int index, int side) {
            return base.Channel.SitDownAsync(userName, index, side);
        }
        
        public void GetUp(int index, int side) {
            base.Channel.GetUp(index, side);
        }
        
        public System.Threading.Tasks.Task GetUpAsync(int index, int side) {
            return base.Channel.GetUpAsync(index, side);
        }
        
        public void Start(string userName, int index, int side) {
            base.Channel.Start(userName, index, side);
        }
        
        public System.Threading.Tasks.Task StartAsync(string userName, int index, int side) {
            return base.Channel.StartAsync(userName, index, side);
        }
        
        public void SetDot(int index, int id) {
            base.Channel.SetDot(index, id);
        }
        
        public System.Threading.Tasks.Task SetDotAsync(int index, int id) {
            return base.Channel.SetDotAsync(index, id);
        }
        
        public void Talk(int index, string userName, string message) {
            base.Channel.Talk(index, userName, message);
        }
        
        public System.Threading.Tasks.Task TalkAsync(int index, string userName, string message) {
            return base.Channel.TalkAsync(index, userName, message);
        }
        
        public void randomplace(int index) {
            base.Channel.randomplace(index);
        }
        
        public System.Threading.Tasks.Task randomplaceAsync(int index) {
            return base.Channel.randomplaceAsync(index);
        }
        
        public void userset(int index, string username, int clickid) {
            base.Channel.userset(index, username, clickid);
        }
        
        public System.Threading.Tasks.Task usersetAsync(int index, string username, int clickid) {
            return base.Channel.usersetAsync(index, username, clickid);
        }
        
        public void TalkToSomebody(string sender, string receiver, string message) {
            base.Channel.TalkToSomebody(sender, receiver, message);
        }
        
        public System.Threading.Tasks.Task TalkToSomebodyAsync(string sender, string receiver, string message) {
            return base.Channel.TalkToSomebodyAsync(sender, receiver, message);
        }
    }
}
