//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadStream", ReplyAction="http://tempuri.org/IService1/DownloadStreamResponse")]
        System.IO.Stream DownloadStream(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadStream", ReplyAction="http://tempuri.org/IService1/DownloadStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadStreamAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilesInfo", ReplyAction="http://tempuri.org/IService1/GetFilesInfoResponse")]
        string[] GetFilesInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilesInfo", ReplyAction="http://tempuri.org/IService1/GetFilesInfoResponse")]
        System.Threading.Tasks.Task<string[]> GetFilesInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Wpf.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Wpf.ServiceReference1.IService1>, Wpf.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream DownloadStream(string fileName) {
            return base.Channel.DownloadStream(fileName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadStreamAsync(string fileName) {
            return base.Channel.DownloadStreamAsync(fileName);
        }
        
        public string[] GetFilesInfo() {
            return base.Channel.GetFilesInfo();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFilesInfoAsync() {
            return base.Channel.GetFilesInfoAsync();
        }
    }
}
